### ISSUE TITLE
unable to build on ubuntu 12.04

### ISSUE THREAD

**Issue by GoogleCodeExporter** [thecocce/aseprite#156]
```
What steps will reproduce the problem?
1.cd build
2.cmake .. -G "Unix Makefiles"
3.make

What is the expected output? What do you see instead?

Scanning dependencies of target grid_ui_unittest
[ 98%] Building CXX object 
src/CMakeFiles/grid_ui_unittest.dir/ui/grid_ui_unittest.cpp.o
Linking CXX executable grid_ui_unittest
../lib/libui-lib.a(overlay.cpp.o): In function 
`ui::Overlay::captureOverlappedArea(she::LockedSurface*)':
/home/bebin/aseprite/src/ui/overlay.cpp:57: undefined reference to 
`she::Instance()'
collect2: ld returned 1 exit status
make[2]: *** [src/grid_ui_unittest] Error 1
make[1]: *** [src/CMakeFiles/grid_ui_unittest.dir/all] Error 2
make: *** [all] Error 2



What version of the product are you using? On what operating system?

ubuntu 12.04 (precise) 64-bit

Kernel Linux 3.2.0-27-generic

```

Original issue reported on code.google.com by `bebinal...@gmail.com` on 12 Aug 2012 at 4:40
