### ISSUE TITLE
0.9 does not build on Ubuntu 10.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [thecocce/aseprite#42]
```
1. Follow the build instrucions
2. make fails

[  1%] Building CXX object CMakeFiles/aseprite-library.dir/modules/gui.o
/home/evan/src/graphics/aseprite/src/modules/gui.cpp:170: error: variable or 
field ‘resize_callback’ declared void
/home/evan/src/graphics/aseprite/src/modules/gui.cpp:170: error: 
‘RESIZE_DISPLAY_EVENT’ was not declared in this scope
/home/evan/src/graphics/aseprite/src/modules/gui.cpp:170: error: ‘ev’ was 
not declared in this scope
make[2]: *** [CMakeFiles/aseprite-library.dir/modules/gui.o] Error 1
make[1]: *** [CMakeFiles/aseprite-library.dir/all] Error 2
make: *** [all] Error 2

Using the latest Aseprite 0.9 from git on Ubuntu 10.3
```

Original issue reported on code.google.com by `erdav...@gmail.com` on 14 Sep 2011 at 3:24
